### PR TITLE
Remix Hallow worldgen is now in the "Hardmode Good" pass

### PR DESCRIPTION
**Pull request by Lion8cake**
Also made the "Hardmode Good" and "Hardmode Evil" pass now run in remix worlds

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
Please fill out the PR description fully using the "new feature" template.

Also, this is fine to do, but you need to avoid formatting/indenting the code, to reduce patch size.

**Comment by Lion8cake** [comment]
where is the new feature template?
is that inside of issues or somewhere else i cant find?

**Comment by Chicken-Bones** [comment]
https://raw.githubusercontent.com/tModLoader/tModLoader/1.4.4/.github/PULL_REQUEST_TEMPLATE/new_feature.md

Normally you'll be directed to use it as part of creating your pull request

**Comment by Chicken-Bones** [comment]
But yes, please fix the formatting of the patches (remove the indent so it doesn't show as removed all lines and then added all lines).

And describe how this benefits mods, what alternative solutions could be considered, a sample of how a mod could make use of the changes etc

**Pull request closed without merging**
