### PR TITLE
more detailed error display when world load/save/clear failes early mod related

### LINKED ISSUE #3401: Improved "World Load Failed" Menu
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

A new, custom menu for displaying proper information about what caused world loading to fail.

### What does this proposal attempt to solve or improve?

The current implementation simply shows `Load Failed! No backup found.`, which is not only inaccurate to the actual problem, but it doesn't give any information about what actually caused the loading to fail.

Most users aren't aware of the `tModLoader/tModLoader-Logs/client.log` file existing, so they only have this misleading information to rely on.

This proposal (and its subsequent PR) aims to completely overhaul this menu by displaying an actual error stacktrace indicating where an exception was thrown.

### Which (other) solutions should be considered?

n/a

### LINKED ISSUE #3988: Modder error in World IO can cause softlock or "net host not responding"
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If a modder's world IO is not properly coded, and exceptions are thrown, these exceptions are not displayed via message box to the player, instead they either softlock the game (immediately after world generation is done), or freeze the game for a few seconds, then give a "net host not responding" window. This is bad for the player because he won't know what mod caused it.

### Log File

Excerpt from two mods that cause this currently

On world exit: (also mirrored in the Natives log!)
```
Silently Caught Exception: 
System.ArgumentException: An item with the same key has already been added. Key: FargowiltasSouls DeviBoss
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Terraria.ModLoader.IO.TagCompound.Set(String key, Object value, Boolean replace) in tModLoader\Terraria\ModLoader\IO\TagCompound.cs:line 74
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BossChecklist.WorldAssist.SaveWorldData(TagCompound tag) in BossChecklist\WorldAssist.cs:line 146
   at Terraria.ModLoader.IO.WorldIO.SaveModData() in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 496
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 31
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 711
   at Terraria.IO.WorldFile.<>c__DisplayClass58_0.<SaveWorld>b__0() in tModLoader\Terraria\IO\WorldFile.cs:line 642
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at DMD<System.Void Terraria.IO.WorldFile:SaveWorld(System.Boolean, System.Boolean)>(Boolean useCloudSaving, Boolean resetTime)
   at SyncProxy<System.Void Terraria.IO.WorldFile:SaveWorld(System.Boolean, System.Boolean)>(Boolean , Boolean )
   at Terraria.IO.WorldFile.SaveWorld() in tModLoader\Terraria\IO\WorldFile.cs:line 617
   at Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2608
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

On worldgen finish
```
Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at MetroidMod.Common.Systems.MSystem.SaveWorldData(TagCompound tag) in MetroidMod\Common\Systems\MSystem.cs:line 339
at Terraria.ModLoader.IO.WorldIO.SaveModData() in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 496
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 31
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 711
   at Terraria.IO.WorldFile.<>c__DisplayClass58_0.<SaveWorld>b__0() in tModLoader\Terraria\IO\WorldFile.cs:line 642
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at Terraria.IO.WorldFile.SaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 641
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2492
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2480
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Steps to reproduce

To reproduce, make a new mod and add this in:
```cs
public class ModWorld : ModSystem
{
    public override void SaveWorldData(TagCompound tag)
    {
        throw new ArgumentException("error that can happen on tagcompounds: 'System.ArgumentException: An item with the same key has already been added'");
        //other common ones are IndexOutOfRangeException and NullReferenceException, usually if uninitialized data is trying to get saved
    }

    public override void LoadWorldData(TagCompound tag)
    {
        base.LoadWorldData(tag);
    }
}
```

Then simply enter a world and quit the world.
For the other scenario, generate a new world, and you will get softlocked after it's finished.

### Expected Behavior

Handle such things more gracefully on tmls end

### Actual Behavior

Softlocks and hard crashes

### Reproduction frequency

100%

### Additional Information
A common reason for the worldgen thing is that modders haven't been properly using the initialization hooks in ModSystem. In 1.3, there used to be only one `Initialize` hook. Then in 1.4 some code changed and it forced modders to override two hooks to achieve the same thing: `OnWorldLoad` and `PreWorldGen`, the latter is usually forgotten during porting. It was then superceded by `ClearWorld` which runs in both contexts like 1.3. If mods are still using the old approach and forgot PreWorldGen, then that issue occurs depending on the type of data the modder has set up.

The code that normally spawns a message box only reacts to certain specific exception types, and none of the common ones mod code can throw.
image

### PR DESCRIPTION
**Pull request by Metratrj**
### What is the bug?
When world load fails no information is displayed which mod is failing

### How did you fix the bug?
Add additional error throwing when mod hooks executed Add displaying error when world load failes mod related on client 

### Are there alternatives to your fix?
No

Should Close #3401
Should Close #3988

### CODE REVIEW

**Comment by Metratrj** [comment]
Close #3988

**Comment by Metratrj** [comment]
@JavidPack What do you think about this?

**Comment by JavidPack** [comment]
It looks sensible, it's on my todo list to test it hopefully today.

**Comment by JavidPack** [comment]
Still reviewing, there are a lot of things for me to test, but it's looking good. I'll continue later.

**Comment by JavidPack** [comment]
Some notes: 

Save-related hooks throwing exceptions crashing or preventing proper saving is troubling, so these exceptions should now be silently caught and logged. Some mod specific data will be lost, but that is better than users losing progress. They don't show an error window because saving happens ingame sometimes. A modder with an error this grievous will find info in the logs.

Player select error button now shows the exception in the info window instead of logging the exception.

Load backup menu has been reworked to restore original "back" and "cancel" buttons, allowing the user to proceed without forcing them to open logs.

https://github.com/tModLoader/tModLoader/assets/4522492/b19cde1e-7366-48ae-884d-43c75fa8c778

**Comment by JavidPack** [comment]
Great work, thanks a lot.

**Pull request merged**
