### PR TITLE
[1.4] Added support for Modded Builder Toggles

### PR DESCRIPTION
**Pull request by xKirtle**
### What is the new feature?
Modded Builder Toggles implementation
### Why should this be part of tModLoader?
To provide a standard way for modders to add their own builder toggles to behave in a similar fashion to vanilla's ones. Requested in #1854 
### Sample usage for the new feature
Included in the Example Mod examples added.
[Functionality showcase imgur link](https://i.imgur.com/gUO2Nww.mp4)
### ExampleMod updates

Included in the video. One builder toggle that is active when the user isn't holding any items and another that is "dimmed" when clicked and its state becomes "Off"

### CODE REVIEW

**Comment by FoxAmes** [comment]
Would love to see this merged, does it need anything other than a rebase to 1.4.4 to be considered?

**Comment by JavidPack** [comment]
I'm not positive how much it needs besides being updated to 1.4.4. We were busy at the time and this one fell through the cracks. I don't imagine it would need much more, I remember it being functional

**Comment by xKirtle** [comment]
Mirsario suggested at the time that another route could be taken instead of ModX and follow the tooltips approach, but I don't think anything was ever settled on. I can revisit this PR and update it to 1.4.4 but would love to know your opinions on which approach should be used.

**Comment by JavidPack** [comment]
Sorry, I forgot to reply it seems. I don't see a way for this to not have a ModX class. The design looks great to me. I want to prioritize this, if you are still around, updating the PR to 1.4.4 shouldn't be too difficult. I noticed builderAccStatus changed slightly, so we'll need to look into that. 

I also noticed looking at the patches that it doesn't seem like saving and loading was implemented. Note how vanilla code needs to be fixed to save the original number of slots, and additional code is needed in PlayerIO to save the modded ones. InfoDisplayLoader is once again a good example of that.

**Comment by JavidPack** [comment]
Port of this PR has been merged. Thanks for putting this together.

**Pull request closed without merging**
