### PR TITLE
fix: mod version selection tests

### LINKED ISSUE #4077: tModLoaderTests (SortingTests) are failing
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Due to the mod version selector update the testsuite can not be builded and the SortingTests(Mod version sorting) are failing.

The LocalMod Class constructor got updated and now have an additional argument and the error messages got changed and now contain version numbers and from where the mod is.

### Log File

_No response_

### Steps to reproduce

1. Run tests

### Expected Behavior

All tests are successful

### Actual Behavior

All tests from SortingTests are failing

### Reproduction frequency

100%

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Metratrj**
### What is the bug?
Test suite build failed and all SortingTests are failing

### How did you fix the bug?
Updated the initialisation of local mod and pass down the newly required argument for mod location
Updated the asserted error messages for mod dependencies

### Are there alternatives to your fix?
No

Closes #4077

### CODE REVIEW

**Comment by Metratrj** [comment]
@Chicken-Bones @Solxanich are any further changes needed?

**Comment by Chicken-Bones** [comment]
~~`LocalMod` isn't sealed. Can you make a subclass for tests and override `ToString`?~~

**Comment by Chicken-Bones** [comment]
On second thoughts, I didn't realise the `.ToString` of `LocalMod` was going to show up in user error messages. We may need to consider changing the reporting in `ModOrganizer` instead

**Comment by JavidPack** [comment]
Thanks for looking into this. After some discussion the changes I made are what we decided was the intended behavior.

**Pull request merged**
