### PR TITLE
Better Solutions

### PR DESCRIPTION
**Pull request by BasicallyIAmFox**
#3293 

### What is the new feature?
Adds new class to be used by modders: `Conversion`.
This attempts to increase readability as well as simplify all the code used by conversions/solutions. (possibly even do some optimizations!)

### Why should this be part of tModLoader?
Currently every single conversion type is just a static method called "Convert" in their custom solution projectile with generally too much repeative code (just like vanilla, I guess) and barely any readability.

### Are there alternative designs?
To Be Discussed.

### Sample usage for the new feature
```
var conversion = new Conversion(FullName);

// Turn all dirt to stone
conversion.ConvertTile(TIleID.Dirt, TileID.Stone).OnConversion(TryKillingTreesAboveIfTheyWouldBecomeInvalid);

conversion.Register();
```

### ExampleMod updates
`ExampleSolution` will be update it to use this new feature.

### CODE REVIEW

**Comment by ilija04** [comment]
ExampleSolution does exist, and it's right here: https://github.com/tModLoader/tModLoader/blob/1.4.4/ExampleMod/Content/Items/Ammo/ExampleSolution.cs

**Comment by BasicallyIAmFox** [comment]
Alright, PR is fully functional I believe. Should be ready for reviews.

**Comment by BasicallyIAmFox** [comment]
Nevermind, this PR slows down hardmode biome gen infinitely.

**Comment by Ouroel** [comment]
> Nevermind, this PR slows down hardmode biome gen infinitely.

It doesn't anymore I believe

**Pull request closed without merging**
