### PR TITLE
Example Swinging Energy Sword (1.4.4 Excalibur Clone)

### PR DESCRIPTION
**Pull request by Rijam**
### What are the changes to ExampleMod?

Adds a long overdue `ExampleSwingingEnergySword` and `ExampleSwingingEnergySwordProjectile` which are a copy of the Excalibur and Excalibur projectile. I'm sure many people would like to have an example on how to make melee weapons that are like the reworked melee weapons in 1.4.4. I chose the Excalibur because it was the simplest of the swords (The Night's Edge and True Night's Edge spawns two projectiles, one of them spins, grows in size, and flies forward. The Terra Blade shoots the long-range projectile. The True Excalibur has multiple layers of the energy. The Horseman's Blade spawns the Flaming Jacks. So, the regular Excalibur was the simplest for an Example Mod example.)

I chose "swinging energy" because the [1.4.4 patch notes](https://terraria.wiki.gg/wiki/1.4.4) describes it as energy and I adding "swinging" so it isn't confused with a light saber type of weapon. Let me know if you think of a better name.

This PR also adds the missing `ProjAIStyleID`s from 1.4.4. Let me know if that should not be included in this PR. Names taken from the AI method names.

Potential feedback:
* I included a copy of the projectile texture so people can use it/modify it if they want. I added a commented out part showing how to use the vanilla texture instead. If you have opinions about this, tell me.
* The drawing of the projectile uses `Main.DrawPrettyStarSparkle()` which is private. I've copied and pasted it into the projectile class to use it, but I was wondering if we should just make it public in Main? I know all the other drawing methods in Main are private, but I feel like DrawPrettyStarSparkle would be useful for easily drawing a pretty effect (similar to the ParticleOrchestra stuff).
* I've included some commented out dusts in Colliding() to visualize the collision. It's adequate for debugging. If anyone wants to improve them, go ahead.
* Some of the drawing stuff looks intimidating and might benefit from more comments.

### Do these changes need additional documentation?
No, unless somebody wants to overhaul the [Vanilla Projectile AIs page](https://github.com/tModLoader/tModLoader/wiki/Vanilla-Projectile-AIs).

Here is a showcase of all of the Particle Orchestra types: https://gist.github.com/Rijam/971b5252707860b65b582093580aa49c

### CODE REVIEW

**Comment by Setnour6** [comment]
This is something that I wanted to have done for #3405 but I wasn't capable of doing so without problems. I'm glad that you are taking the initiative to make that a real thing.

Upon testing, I noticed that the dust that appears from each sword swing is the same as the regular Excalibur. Do you think that using the example sparkle dust is better, just to show that any dust can be used rather than to only have the default dusts appear?
Additionally, do you think that you can include other shoot effects but have them commented out, just so modders can see that it is possible to add other shoot effects (like the horseman's blade pumpkins, or the night's edge new projectiles)?
Finally, are you able to provide a blue color to the "enemy hit" sparkle draw? It still shows as yellow when an enemy is hit, which is fine, but just in case modders want to use a different color for the sparkles.
image
Ultimately, it's up to you, and it depends on what the developers say.

Regardless, everything is good.

**Comment by Rijam** [comment]
I tried to keep it a clone as much as possible (except the colors of course). For the swinging dusts, you can change the color of them. I probably won't include the other types of swords. But, here is how the Horseman's Blade spawns its pumpkins (add this to OnHitNPC):
```cs
// Here is how the Horseman's Blade spawns the Flaming Jack projectiles.
if (!target.immortal && !target.SpawnedFromStatue && !NPCID.Sets.CountsAsCritter[target.type]) {
	// Unfortunately, this method is hard coded to always use the Flaming Jack projectiles.
	// Main.player[Projectile.owner].HorsemansBlade_SpawnPumpkin(target.whoAmI, Projectile.damage, Projectile.knockBack);

	// Here is what the method does. Change the ProjectileID to whatever projectile you want.
	Player player = Main.player[Projectile.owner];
	Vector2 center = Main.npc[target.whoAmI].Center;
	int logicCheckScreenHeight = Main.LogicCheckScreenHeight;
	int logicCheckScreenWidth = Main.LogicCheckScreenWidth;
	Vector2 pos = new(Main.rand.Next(100, 300), Main.rand.Next(100, 300));
	pos.X = (!Main.rand.NextBool(2)) ? (pos.X + (logicCheckScreenWidth / 2 - pos.X)) : (pos.X - (logicCheckScreenWidth / 2 + pos.X));
	pos.Y = (!Main.rand.NextBool(2)) ? (pos.Y + (logicCheckScreenHeight / 2 - pos.Y)) : (pos.Y - (logicCheckScreenHeight / 2 + pos.Y));
	pos += new Vector2((int)player.position.X, (int)player.position.Y);
	Vector2 speed = center - pos;
	float distance = (float)Math.Sqrt(speed.X * speed.X + speed.Y * speed.Y);
	distance /= 8f;
	speed *= distance;
	Projectile.NewProjectile(player.GetSource_ItemUse(player.HeldItem), pos, speed, ProjectileID.FlamingJack, Projectile.damage, Projectile.knockBack, player.whoAmI, target.whoAmI);
}
```

The sparkle is part of vanilla's Particle Orchestra. There isn't a way to customize the color.

**Comment by JavidPack** [comment]
Looks good. I'm not sure about making public DrawPrettyStarSparkle, it seems a very narrow use-case, we might want modders to learn to copy the code and tweak it rather than have them assume they can only use the specific existing methods.

Good job.

**Comment by Setnour6** [comment]
> The sparkle is part of vanilla's Particle Orchestra. There isn't a way to customize the color.

Are you sure about that?

https://github.com/tModLoader/tModLoader/assets/70764728/729076a5-d9f2-4fb4-97cc-5c90ce6b5417

> I'm not sure about making public DrawPrettyStarSparkle, it seems a very narrow use-case, we might want modders to learn to copy the code and tweak it rather than have them assume they can only use the specific existing methods.

There could be tons of cool and unique applications for the pretty star sparkles. I haven't thought about what specific things could benefit from it though, but advanced modders could make a lot of use out of it for their projectiles and whatnot.

**Comment by JavidPack** [comment]
My point was the DrawPrettyStarSparkle method itself uses a specific texture, modders are better off using it as a guide rather than just using the method as it is.

Is changing that hit color a lot of work? I can add it if we want.

**Comment by Setnour6** [comment]
> My point was the DrawPrettyStarSparkle method itself uses a specific texture, modders are better off using it as a guide rather than just using the method as it is.

I get it now. I guess public pretty star sparkle won't happen.

> Is changing that hit color a lot of work? I can add it if we want.

It took me almost 10 hours to get it working. I haven't tested it in multiplayer though, because the mod that the sword is from does not have multiplayer compatibility (it's from Everglow, ported from MythMod).
Basically, I copied `Spawn_Excalibur` from `Terraria.GameContent.Drawing.ParticleOrchestra` and made changes to the color and method parameters.
```cs
private static PrettySparkleParticle GetNewPrettySparkleParticle() => new PrettySparkleParticle();
	private static ParticlePool<PrettySparkleParticle> _poolPrettySparkle = new ParticlePool<PrettySparkleParticle>(200, GetNewPrettySparkleParticle);
	/// <summary>
	/// A custom version of Spawn_Excalibur from Terraria.GameContent.Drawing.ParticleOrchestra
	/// </summary>
	/// <param name="settings">The Particle Orchestra Settings</param>
	/// <param name="colorTint1">The First Color Tint of the Sparkle</param>
	/// <param name="colorTint2">The Second Color Tint of the Sparkle. Leave empty to default to colorTint1</param>
internal static void Spawn_CustomColorExcalibur(ParticleOrchestraSettings settings, Color colorTint1, Color colorTint2 = default)
	{
		if (colorTint2 == default)
			colorTint2 = colorTint1;
		float num = 30f;
		float num2 = 0f;
		for (float num3 = 0f; num3 < 4f; num3 += 1f)
		{
			PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
			Vector2 vector = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 2f; // Was 4f;
			prettySparkleParticle.ColorTint = colorTint1; // Originally new Color(0.9f, 0.85f, 0.4f, 0.5f);
			prettySparkleParticle.LocalPosition = settings.PositionInWorld;
			prettySparkleParticle.Rotation = vector.ToRotation();
			prettySparkleParticle.Scale = new Vector2((num3 % 2f == 0f) ? 2f : 4f, 0.5f) * 1.1f;
			prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
			prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
			prettySparkleParticle.TimeToLive = num;
			prettySparkleParticle.FadeOutEnd = num;
			prettySparkleParticle.FadeInEnd = num / 2f;
			prettySparkleParticle.FadeOutStart = num / 2f;
			prettySparkleParticle.AdditiveAmount = 0.35f;
			prettySparkleParticle.Velocity = -vector * 0.2f;
			prettySparkleParticle.DrawVerticalAxis = false;
			if (num3 % 2f == 1f)
			{
				prettySparkleParticle.Scale *= 1.5f;
				prettySparkleParticle.Velocity *= 1.5f;
			}

			Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
		}

		for (float num4 = 0f; num4 < 4f; num4 += 1f)
		{
			PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
			Vector2 vector2 = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 2f; // Was 4f;
			prettySparkleParticle2.ColorTint = colorTint2; // Originally new Color(1f, 1f, 0.2f, 1f)
			prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
			prettySparkleParticle2.Rotation = vector2.ToRotation();
			prettySparkleParticle2.Scale = new Vector2((num4 % 2f == 0f) ? 2f : 4f, 0.5f) * 0.7f;
			prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
			prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
			prettySparkleParticle2.TimeToLive = num;
			prettySparkleParticle2.FadeOutEnd = num;
			prettySparkleParticle2.FadeInEnd = num / 2f;
			prettySparkleParticle2.FadeOutStart = num / 2f;
			prettySparkleParticle2.Velocity = vector2 * 0.2f;
			prettySparkleParticle2.DrawVerticalAxis = false;
			if (num4 % 2f == 1f)
			{
				prettySparkleParticle2.Scale *= 1.5f;
				prettySparkleParticle2.Velocity *= 1.5f;
			}

			Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
			for (int i = 0; i < 1; i++)
			{
				Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 92, vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
				dust.noGravity = true;
				dust.scale = 1.4f;
				Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 92, -vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
				dust2.noGravity = true;
				dust2.scale = 1.4f;
			}
		}
	}
```


The next thing I did was change the logic of the `OnHitNPC` overridden method to instead display the following:
```cs
Spawn_CustomColorExcalibur(new ParticleOrchestraSettings { PositionInWorld = Main.rand.NextVector2FromRectangle(target.Hitbox) }, new Color(0f, 0.5f, 0.6f, 0.5f), new Color(0f, 0.82f, 0.82f, 1f));
```

Overall, it works, but multiplayer testing hasn't been conducted yet and might not work. You can try to copy the weapon and projectile onto your own testing mod for the sake of testing with multiplayer and use it near other players.

the item is called `CyanFrost` internally and the projectile is called `CyanFrostProj`. They are located under the "Myth" module in Sources -> Modules -> Myth -> Misc (branches from here) -> Items -> Weapons. Projectiles -> Weapon -> Melee.
[Solaestas/Everglow, Myth/Cyfrost-Blade-Opt branch](https://github.com/Solaestas/Everglow/tree/Myth/Cyfrost-Blade-Opt)

To test it under the Everglow mod, you have to build the mod and run it through Visual Studio. Then make a new character and world, enter the world, and give yourself through HERO's Mod, Cheat Sheet, DragonLens, the weapon that is displayed as "Cyan Frost" or "Cyfrost Blade"

**Pull request merged**
