### PR TITLE
[1.4] Update Spanish localization

### PR DESCRIPTION
**Pull request by Wolf-Igmc4**
Updated the translations with the ones that appear at the English file (except for the placeholders). Tweaked some of the older ones.

### CODE REVIEW

**Comment by Solxanich** [comment]
Apologies, another PR was merged that conflicts with this one.
Can you update your PR to address the conflicts?

**Comment by Setnour6** [comment]
Here is the text that conflicts, but you can use for translating:

"TagsContent": "New Content",
		"TagsContentDescription": "Adds new content (i.e. items, weapons, npcs, etc.) to the game",
		"TagsUtility": "Utilities",
		"TagsUtilityDescription": "Adds utility-oriented content or features",
		"TagsLibrary": "Library",
		"TagsLibraryDescription": "Provides additional API & features useful to modders",
		"TagsQoL": "Quality Of Life",
		"TagsQoLDescription": "Features or changes that reduce time spent on typically less fun tasks.",
		"TagsGameplay": "Gameplay Tweaks",
		"TagsGameplayDescription": "Tweaks that change or improve vanilla gameplay",
		"TagsAudio": "Audio Tweaks",
		"TagsAudioDescription": "Tweaks that change existing audio (i.e. new boss themes, etc.)",
		"TagsVisual": "Visual Tweaks",
		"TagsVisualDescription": "Tweaks that change existing visualization (i.e. particle effects, etc.)",
		"TagsLang": "Localization Support",
		"TagsLangDescription": "This mod supports multiple languages",
		"TagsGen": "Custom World Gen",
		"TagsGenDescription": "Changes the way the world is generated (i.e. ores, new structures, etc.)"

**Comment by Wolf-Igmc4** [comment]
Thanks for letting me know! I've added the descriptions and changed the translations corresponding to MonthlyFreezeNotification, FirstLaunchWelcomeMessage and WhatsNewMessage (since they got updated in another PR).

**Comment by Jofairden** [comment]
Thx a bunch!

**Pull request merged**
