### PR TITLE
Added example laser beam weapon

### PR DESCRIPTION
**Pull request by CXUtk**

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
Looks good to me

**Comment by JavidPack** [comment]
The item namespace and PNG location don't match up, the cs file and PNG file should be moved to the weapons folder so it actually loads. Did you test on mp?

**Comment by CXUtk** [comment]
I think they are match, one is weapon and one is projectile. I actually tested them.

**Comment by JavidPack** [comment]
What I mean is, the ExampleLaserWeapon ModItem is in ExampleMod.Items.Weapons namespace, but in the ExampleMod/Items/ folder. Autoloading the textures will fail since the namespace and folder of the png don't match.

**Pull request merged**
