### PR TITLE
Fix IME compability issue

### LINKED ISSUE #2571: Input method panel accidently shown
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

[Input method](https://en.wikipedia.org/wiki/Input_method) shows when it shouldn't. Really annoying.

We can play normally though if we turn on the Caps Lock, this way the IME never shows up. However, I wonder why it happens in tModLoader 1.4, but works properly in vanilla Terraria. Also, it will be better if it is really fixed.

### Log File

_No response_

### Steps to reproduce

1. Install an input method to your computer. Maybe [this](https://answers.microsoft.com/en-us/windows/forum/all/traditional-chinese-pinyin-keyboard-in-window-10/9353f1ee-589a-48c8-ab64-0748722eb79c?page=1) tutorial helps?
2. Select the input method you just installed.
3. Open tModLoader 1.4 and just randomly click some keys

### Expected Behavior

For us Chinese, we use [input methods](https://en.wikipedia.org/wiki/Input_method) to input Chinese characters
Terraria has a custom IME panel system. For example, the following code in Main.DrawPlayerChat()
```
string compositionString = Platform.Get<IImeService>().CompositionString;
if (compositionString != null && compositionString.Length > 0)
	list.Add(new TextSnippet(compositionString, new Microsoft.Xna.Framework.Color(255, 240, 20)));
```
```
if (drawingPlayerChat && array != null) {
	Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, array, Vector2.Zero);
	DrawWindowsIMEPanel(new Vector2(88f, screenHeight - 30) + new Vector2(stringSize.X + 10f, -6f));
}
```
It will be like this in game, at least in vanilla Terraria
image
Then we can press the number to select the Chinese character(s) we want from the panel

In vanilla Terraria and tModLoader 1.3, the panel only shows when the game wants you to input something. For example, it only shows up when you chat, edit the name of a chest, or write a sign.

### Actual Behavior

In tModLoader 1.4, the system's IME panel shows whenever you press a key. It just simply thinks you are editing a sign while playing tModLoader.
Also, the method Main.DrawWindowsIMEPanel() becomes completely useless, since the game just uses system IME panel in the bottom right corner, like this.

(The [Microsoft Pinyin IME](https://en.wikipedia.org/wiki/Microsoft_Pinyin_IME) shows up because I'm using it)

### Reproduction frequency

Always

### Additional Information

It has never been an issue until this: #1086, when tModLoader became 64-bit and started showing console.
Interestingly, the 1.3 unofficial 64-bit tModLoader also has this problem.

So maybe it's FNA's fault?
Or the system consider tML a console that requires input?
image

### PR DESCRIPTION
**Pull request by HydroH**
### What is the bug?
Issue #2571 and #3095 
### How did you fix the bug?
In vanilla Terraria, the system IME is hidden and uses a game-drawn IME that retreives information from `Relogic.Native.dll`, in `ReLogic.Localization.IME.Windows.NativeMethods`:
```
[DllImport("ReLogic.Native.dll", CharSet = CharSet.Unicode, EntryPoint = "ImeUi_EnableIme")]
	public static extern void ImeUi_Enable([MarshalAs(UnmanagedType.I1)] bool bEnable);

[DllImport("ReLogic.Native.dll", CharSet = CharSet.Unicode)]
	public static extern IntPtr ImeUi_GetCompositionString();
```
etc.

The dll is compiled in 32-bit and tModLoader removed related code after upgrading to 64-bit.

After looking into the dll, I found it called imm32.dll methods. Thus, IME related native methods could be rewritten using P/Invoke functions in imm32.dll.
I wrote a `ImmWrapper` class that re-implements methods in `Relogic.Native.dll`, making the IME compatible.

### CODE REVIEW

**Comment by 312784123** [comment]
Wow! if there is no problem, Could you please upload at workshop? I think mod is easier for people to use IME before tmodloader updates.


I rellay appreciate your work. Thanks!!!

**Comment by HydroH** [comment]
> Wow! if there is no problem, Could you please upload at workshop? I think mod is easier for people to use IME before tmodloader updates.
> 
> I rellay appreciate your work. Thanks!!!

Unfortunately IME handling is heavily integrated into Terraria's core code, I don't think it's very possible to make it work as a separate mod.

**Comment by 312784123** [comment]
So sad. Thanks.

**Comment by 312784123** [comment]
issue



Another Problem happens. Fixing Korean IME is fine, No problem. But English is typed twice. Acutally, Same issue happens in Vanilla Terraria but Korean IME(English is fine. but Korean types twice, so korean users in vanilla uses program to fix this issue).
 I dont' know this similar issue in vanilla is relevant.

**Comment by HydroH** [comment]
> issue [ issue ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif) [ ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> 
> Another Problem happens. Fixing Korean IME is fine, No problem. But English is typed twice. Acutally, Same issue happens in Vanilla Terraria but Korean IME(English is fine. but Korean types twice, so korean users in vanilla uses program to fix this issue). I dont' know this similar issue in vanilla is relevant.

Hi, thanks for reporting. If the vanilla Terraria behaves the same way, that's my "desired" behavior for this patch, because what I did is basically re-implementing the vanilla Terraria IME handling.
I will probably look into this and maybe fix it in a separate PR though, along with other vanilla IME issues.

**Comment by HydroH** [comment]
Move this to `TerrariaNetCore` patch in #3375 .

**Comment by Chicken-Bones** [comment]
> issue [ issue ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif) [ ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> 
> Another Problem happens. Fixing Korean IME is fine, No problem. But English is typed twice. Acutally, Same issue happens in Vanilla Terraria but Korean IME(English is fine. but Korean types twice, so korean users in vanilla uses program to fix this issue). I dont' know this similar issue in vanilla is relevant.

I'm pleased to report that the Korean IME will be fixed in Terraria 1.4.5

**Comment by 312784123** [comment]
> > issue
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> >         
> >             issue
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> >         
> >        [ issue ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> >         
> >             issue
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/118354239/229263156-31f32398-149e-4c2e-bc65-87911f808bb4.gif)
> > Another Problem happens. Fixing Korean IME is fine, No problem. But English is typed twice. Acutally, Same issue happens in Vanilla Terraria but Korean IME(English is fine. but Korean types twice, so korean users in vanilla uses program to fix this issue). I dont' know this similar issue in vanilla is relevant.
> 
> I'm pleased to report that the Korean IME will be fixed in Terraria 1.4.5

Awesome. That's nice. Thanks!

**Pull request closed without merging**
