### PR TITLE
Disabeable item drop rules

### PR DESCRIPTION
**Pull request by BasicallyIAmFox**
### What is the new feature?
Adds `IItemDropRule.Disabled` property

### Why should this be part of tModLoader?
See #3733 

### Are there alternative designs?
The one and patch heavy is adding common, base item drop rule class and make every drop rule inherit it. Additionally commenting out most item drop rule fields and properties.

### Sample usage for the new feature
See ExampleMod updates.

### ExampleMod updates
Added example of disabling Reaper's Death Sickle drop rule.

### CODE REVIEW

**Comment by Jacklz** [comment]
Should adding/disabling loot be prevented during the game and only permitted during reload? Like with recipes.

**Comment by BasicallyIAmFox** [comment]
> Should adding/disabling loot be prevented during the game and only permitted during reload? Like with recipes.

i dont see any realistic reason why anyone would do that tbh

**Comment by Jacklz** [comment]
> > Should adding/disabling loot be prevented during the game and only permitted during reload? Like with recipes.
> 
> i dont see any realistic reason why anyone would do that tbh

i dont see why either, but its more about consistency and taking precautions. Why were recipes locked to reload only?

**Comment by Chicken-Bones** [comment]
> > > Should adding/disabling loot be prevented during the game and only permitted during reload? Like with recipes.
> > 
> > 
> > i dont see any realistic reason why anyone would do that tbh
> 
> i dont see why either, but its more about consistency and taking precautions. Why were recipes locked to reload only?

So that mods can perform computations at load time like whether an item is a material, or which recipes can be used to craft an item, without re-checking the enabled conditions every frame/whenever

**Comment by direwolf420** [comment]
I think it would be nicer if `npcLoot.Get()` would have a new parameter that by default only returns non-disabled rules, that way modders don't have to add `IsDisabled` checks anywhere

**Comment by BasicallyIAmFox** [comment]
> I think it would be nicer if `npcLoot.Get()` would have a new parameter that by default only returns non-disabled rules, that way modders don't have to add `IsDisabled` checks anywhere

Err, that's very likely to be breaking change then... But if that dotnetbuild pr gets merged this month then its fine i think. Its only breaking change pr so far i know?

**Comment by Jacklz** [comment]
I noticed in the ExampleMod examples for disabling loot, you have to explicitly define the type of loot you're disabling with the class name. If you're trying to disable loot from other mods, you're most likely not going to know the class name or the fields within that class without decompiling that mod or looking at its source if its even open.

Also some items like loot bags can be a single IItemDropRule type with multiple items defined to drop but have no friendly way to remove or add a single item to/from that individual drop rule, especially if a mod is using a custom class inheriting the IItemDropRule interface.

Is there a way to make this easier?

**Comment by BasicallyIAmFox** [comment]
> I noticed in the ExampleMod examples for disabling loot, you have to explicitly define the type of loot you're disabling with the class name. If you're trying to disable loot from other mods, you're most likely not going to know the class name or the fields within that class without decompiling that mod or looking at its source if its even open.
> 
> Also some items like loot bags can be a single IItemDropRule type with multiple items defined to drop but have no friendly way to remove or add a single item to/from that individual drop rule, especially if a mod is using a custom class inheriting the IItemDropRule interface.
> 
> Is there a way to make this easier?

sounds like something out of the scope of this pr. (#2759)

**Comment by Jacklz** [comment]
> > I noticed in the ExampleMod examples for disabling loot, you have to explicitly define the type of loot you're disabling with the class name. If you're trying to disable loot from other mods, you're most likely not going to know the class name or the fields within that class without decompiling that mod or looking at its source if its even open.
> > Also some items like loot bags can be a single IItemDropRule type with multiple items defined to drop but have no friendly way to remove or add a single item to/from that individual drop rule, especially if a mod is using a custom class inheriting the IItemDropRule interface.
> > Is there a way to make this easier?
> 
> sounds like something out of the scope of this pr. (#2759)

Oh i forgot about this PR. Thanks for linking. I have some crude ideas for it that i may post about there when i get around to finishing my ideas.

**Comment by BasicallyIAmFox** [comment]
@Chicken-Bones can you review this any time soon?

**Comment by Chicken-Bones** [comment]
We've stalled out a bit on this because we need to decide whether disabled rules should be returned by various calls to the loot system aside from actual rolling. We need to come up with a clear set of guidelines for how to _use_ the loot system, and without these it's hard to know whether this feature will create more confusion.

When mods are searching for places to add their loot to existing pools, should disabled rules be returned? What if mods want to remove an item from a `OneFromOptionsDropRule`?

We really need to do a review of current modded usages of the loot system and identify all the times that destructive changes are made (removing/restructuring rules) and determine if we can support these use cases explicitly. Then we can reason about how to make simple changes (such adding or removing an item from a loot pool) compatible with more drastic ones.

**Pull request closed without merging**
