### PR TITLE
Update ru-RU tModLoader.hjson

### PR DESCRIPTION
**Pull request by RazzSG**
I reverted Blueberryy's translation edits. It looks like this guy has never played Terraria before.

### CODE REVIEW

**Comment by Blueberryy** [comment]
Sorry if i confused you but i did played Terraria and some of stat tooltip changes was from the mod that improves Russian localization.

**Comment by Blueberryy** [comment]
By the way, i did some review and i hope you will answer to my questions on it :p

**Comment by RazzSG** [comment]
That's right. All changes were made taking into account the mod that everyone uses and which fixes the Russian vanilla localization. No one in the russian community uses or writes "Полож. эфф.", "Сложный режим", "Персонажи", "Журнал", "Многопользовательская игра", ect. These are all game terms and they are not translated like that in the context of this game.

**Comment by Blueberryy** [comment]
Okay but what about quotation marks (")and (') i think they mostly replaced to guille­mets («) and (») in Russian even in official Terraria translation.

**Comment by Blueberryy** [comment]
Anyway i think this can be merged. Didn't liked Terraria anyway

**Comment by JavidPack** [comment]
Mirsario will take a look, he knows Russian and can guide this discussion.

**Comment by RazzSG** [comment]
This is not the best place for such a discussion. If you have discord, add me as a friend, we can discuss things there. Discord tag: razzsg

**Review by Mirsario — APPROVED** [review]
Merging with these changes:
- Undid guillemet reverts around **static** Russian text, since the vanilla localization does make use of them a lot. English quotes are kept for dynamic text, English text, and IO paths.
- "File" or "Folder" suffixed to English-borrowed "log" words.

Everything else is fair improvements if aforementioned transliterations/borrowings is what the community is used to, but please don't be so absolute with statements such as:
> It looks like this guy has never played Terraria before.

Thanks.

**Pull request merged**
