### PR TITLE
use native Win32 platform version of FAudio instead of ffmpeg

### PR DESCRIPTION
**Pull request by ubnt-intrepid**
### What is the bug?

On Windows, BGM is intermittently interrupted at short intervals (refs: #1693, [forum thread]).

[forum thread]: https://forums.terraria.org/index.php?threads/im-new-to-troubleshooting-terraria-mod-issues.98816/

As mentioned in the thread above, the following log messages were dumped on interrupting the BGM:
```
[wmav2 @ 0000025d2446f840] overflow (1865 > 1864) in spectral RLE, ignoring
```

These log messages were due to ffmpeg, and a similar problem was reported on their issue tracker:
* https://trac.ffmpeg.org/ticket/691

I also experimented by replacing ffmpeg DLLs in `Libraries/Natives` with the latest 4.4.1 build, but it didn't solve the slutter problem.

### How did you fix the bug?

This patch forces FAudio backend to use the native Win32 audio platform instead of ffmpeg on Windows. 

* Upgrade `FAudio.dll` to the upstream version with `PLATFORM_WIN32=ON`
* Remove unnecessary DLLs from ffmpeg

<details>
<summary>Build information</summary>

Environment:
  * Windows11, MinGW-w64 on MSYS2
  * `MINGW64_NT-10.0-22000 DESKTOP-XXXXXX 3.2.0-340.x86_64 2021-08-02 16:30 UTC x86_64 Msys`

Instructions:
```shell-session
$ echo "$(pwd), $(git rev-parse --short HEAD)"
/d/Sources/FAudio, de0c1f8

$ mkdir _build && cd $_
$ cmake -DPLATFORM_WIN32=ON ../
$ ninja
$ ls
... FAudio.dll ...
```

</details>

### Are there alternatives to your fix?

* Build FAudio during setup rather than including pre-build DLLs.

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
Interesting. When did FAudio add the platform win32 option? Does it work on all versions of windows?

**Comment by ubnt-intrepid** [comment]
> When did FAudio add the platform win32 option?

Since [21.07](https://github.com/FNA-XNA/FAudio/releases/tag/21.07). A concern is that they mention this feature as "experimental", but it seems to work fine at least in my environment. 

> Does it work on all versions of windows?

The native Win32 platform backend [uses Windows Core Audio API](https://docs.microsoft.com/en-us/windows/win32/coreaudio/core-audio-apis-in-windows-vista), that introduced in Vista and improved in Windows7, and it should be work on most of upstream Windows versions. I'm sorry but I don't currently own the older versions of Windows and it has not be tested yet.

**Comment by Solxanich** [comment]
Quick question here;
Is the bug confirmed only observed on Windows?
Just want to identify if a similar change needs to be considered for Unix platforms.
Beyond that, has this been tested with mods that add Music, such as ExampleMod's example biome? Want to make sure we aren't breaking anything mods wise

**Comment by Chicken-Bones** [comment]
The mention of wmav2 codec means it should only affect tracks from the vanilla wavebank

**Review by Mirsario — APPROVED** [review]
Seems to be working well, thanks. GStreamer being removed is really great news -- It was such a pain to deal with that I legit rolled back FAudio to using ffmpeg directly.

**Pull request merged**
