### PR TITLE
add some german translations

### PR DESCRIPTION
**Pull request by Metratrj**

### CODE REVIEW

**Comment by JavidPack** [comment]
Looking good so far.

**Comment by JavidPack** [comment]
A new month/release is coming soon. Is this in a suitable place to merge? I see there are still some missing, but those can be done later. Better to have some in now than wait. 

Right now it is marked as a "Draft", so I just wanted to check.

**Comment by Metratrj** [comment]
Adding today some more translations than I will mark this ready to merge. When is the deadline for this?

**Comment by JavidPack** [comment]
Thanks. I merged this. Feel free to open a new PR if you want to continue with any other still untranslated entries. I didn't mean to rush you, we just try to get edits in before each month starts. The changes you've made here will be in preview in March and stable in April, unless we happened to bring them into stable earlier.

**Pull request merged**
