### PR TITLE
Steam Store Page zh-Hans Localization

### PR DESCRIPTION
**Pull request by lace-wing**
### What is the new feature?

Simplified Chinese translation for tModLoader's Steam Store Page (needs manual uploads though).

### Why should this be part of tModLoader?

So that Chinese readers can better understand what it is.

### CODE REVIEW

**Comment by JavidPack** [comment]
I'm not quite sure what to do about the overlap between this and #3858, can you two talk and maybe consolidate the best translations into a single PR? I'm not really able to judge which is better myself.

**Comment by ayuyoiM** [comment]
I don’t know how to solve it either_(:з」∠)_

Maybe it's better to merge? (This PR merges with my PR)

**Comment by lace-wing** [comment]
I see, what a coincidence, will try resolving the different translations.
To be honest I'm not cool with Fish-cat-cat's translations as there are improper or non-comprehendible expressions.
In my opinion this PR can be merged while rest of the translations can be improved.
Still I'll contact Fish-cat-cat, @Fish-cat-cat may I have your username/identity (best if Discord, else QQ or WhatsApp)?

**Comment by ayuyoiM** [comment]
> In my opinion this PR can be merged while rest of the translations can be improved.
> Still I'll contact Fish-cat-cat, @Fish-cat-cat may I have your username/identity (best if Discord, else QQ or WhatsApp)?

Discord username: fish_cat_cat (Maybe you can find me in tModloader server)

**Comment by lace-wing** [comment]
@JavidPack We've discussed about it, and here are the follow-ups:
- this PR can be merged
- Steam Page translations in #3858 will be discarded, and Fish-cat-cat will quickly make some changes to the rest

**Comment by JavidPack** [comment]
Sounds good.

**Pull request merged**
