### PR TITLE
Localization support for ModConfig

### PR DESCRIPTION
**Pull request by lace-wing**
### What is the new feature?
-Localization support for ModConfig
-Chinese translation for ModConfig
### Why should this be part of tModLoader?
-It's considered as a TODO
-Localization helps those who are not English speakers to understand what are the features of ModConfig
### Are there alternative designs?
-Since other localizations are using the .json files in the Localization folder, I just did it in the same way
-I don't see any better design, but is there is, I'll be willing to change
### Sample usage for the new feature
-Localizers can easily add/modify the translations in corresponding .json files

### CODE REVIEW

**Comment by lace-wing** [comment]
@JavidPack This is just a tiny simple localization PR but can improve the QoL of both players and community moderators, may I have you to look at it?
OwO

**Comment by JavidPack** [comment]
I noticed that all the other language files mistakenly have the English translations set in them, they should be commented out.

**Comment by lace-wing** [comment]
That's because I couldn't translate them into other languages. Maybe I can find someone I know to do the ru-RU part, then we just merge this PR and wait others to do the rest

**Comment by JavidPack** [comment]
I'm not asking you to translate them. They all need the "//" in front of them except the English and Chinese.

**Comment by lace-wing** [comment]
Okay done

**Comment by JavidPack** [comment]
Looks good, thanks.

**Comment by JavidPack** [comment]
wait, you didn't build this PR?

**Comment by lace-wing** [comment]
What do you mean by "build this PR", before creating this PR I've tested it on a dev-tML, everything looks fine

**Comment by JavidPack** [comment]
Language.GetText returns a LocalizedText object, not a string. I changed them all to Language.GetTextValue already. Strange that it built fine for you.

**Pull request merged**
