### PR TITLE
[1.4] Simple itemAnimation mismatch patch and itemTime now passing trough zero

### PR DESCRIPTION
**Pull request by DarioDaF**
Demonstration patch of zero itemAnimation needed in AI_019_Spears for Kill

### What is the bug?
https://github.com/tModLoader/tModLoader/issues/1773

### How did you fix the bug?
Forcing item to act at the end of the frame (but cutting the method so that AI processing boundries are in the middle).

### Are there alternatives to your fix?
Anything else is probably better, a discussion should be done on the need to have consistent animation and time variables (if the issue was the animation an use time desync there are other ways around it keeping them desynced by a constant 1 frame instead of have them overlap).

This is probably the hackiest fix possible, just keeping vanilla order of times etc without the "spagetti" rework solves the issue too and why it was reworked that way (with actual mod examples or bugs that vanilla would make hard to solve).

### CODE REVIEW

**Comment by DarioDaF** [comment]
tML current behaviour with `useStyle` of no autoswing sword: 
image

**Comment by DarioDaF** [comment]
With this patch: 
image

**Comment by DarioDaF** [comment]
Feral Claw swing with PR: 
image

As seen itemAnimation never gets down to 0, making the swing take 1 frame less.
While this patch and no `goto` (aka vanilla order) pass trough `itemAnimation == 0`

**Comment by DarioDaF** [comment]
Lance behaviour, no 0 means no cleanup of projectiles: LanceTML

Guns somehow never get to 0 no matter what: GunTML

So if the idea is to keep al "resetting" on 1s (having last animation being 1 frame longer as an effect) all the places outside `ItemCheck` in vanilla code need to be fixed by subtracting one? so taking this as a base PR and removing the frame skip part (so it's like tML but with the reuse bugs, those reuse will be fixed by the subtract 1 on vanilla)

**Comment by DarioDaF** [comment]
None of the above present desync (due to the fact that max animation is supposed to always be 1 less than use time in vanilla when they matter).

**Comment by DarioDaF** [comment]
Final push of what I will be testing locally that will potentially become obsolete when Thomas finds an alternative solution (mine moves all `itemTime` to pass trough 0, autoReuse or not (without changing the actual frame counted useTime ofc).

**Comment by Chicken-Bones** [comment]
Superceded by #2351

**Pull request closed without merging**
