### PR TITLE
[1.4] Allow usage of non public constructors

### PR DESCRIPTION
**Pull request by ExterminatorX99**
### What is the bug?
#2403 

### How did you fix the bug?
Allow non public constructors

### Are there alternatives to your fix?
Custom exception message saying we only support public constructors

### CODE REVIEW

**Comment by JavidPack** [comment]
Reminder: We might need to also address #2332 (latest comments) at the same time.

**Comment by Chicken-Bones** [comment]
We would like the alternative "custom error message saying that the default constructor must be public". We do this to reduce confusion about auto-loading. A `public` constructor is 'meant for public (outside) use', a `private` one may be assumed to only be used within the class, and autoloading comes in and calls it causing confusion. 

I see no benefit to allowing autoloading via non-public constructors.

**Comment by direwolf420** [comment]
Just wanted to throw this in:
https://github.com/tModLoader/tModLoader/blob/ada8c2396bad92fd51abc37337fee1613037e1c0/patches/tModLoader/Terraria/ModLoader/Mod.Internals.cs#L55-L64

It currently already uses `nonPublic` for `Activator.CreateInstance` here (which is valid as the check above also includes `NonPublic` flag)

**Comment by Chicken-Bones** [comment]
@direwolf420 thanks for the update, ugh, regret... Something for the 1.4.4 breaking change list? or do we just say whatever

**Comment by JavidPack** [comment]
I've kept many things internal in my mods so that other mods referencing it only see the public API that I provide. I think tmodloader accessing them is expected of a mod loader, but the access modifiers in my mods are for cross mod and in mod considerations only. Having to cater to tmodloader in this way would expose other classes I don't want mods referencing my mod to have to sift through. The Mod class could be special though, since it is the main way to access many things you'll need in a cross mod situation. I don't mind the apparent contradiction with that.

**Pull request merged**
