### PR TITLE
Common Tooltips

### PR DESCRIPTION
**Pull request by Chik3r**
### What is the new feature?
Common tooltips translated to various languages (I have only translated to EN and ES rn)
There is an issue for this: #540 

### Why should this be part of tModLoader?
Because it will allow mods to have common tooltips available on various languages without any need to translate them

### Are there alternative designs?
Maybe

### Sample usage for the new feature
```csharp
using Terraria.Localization;

...

Tooltip.SetDefault(Language.GetTextValue("CommonItemTooltip.PercentIncreasedCritChanceClass", 20, Language.GetTextValue("CommonItemTooltip.ClassRanger"))); 
// {0}% increased {1} critical strike chance - where {0} is the CritChance increase (here it's 20) and {1} is the class (here it's ranger, and we get its text with GetTextValue)

Tooltip.SetDefault(Language.GetTextValue("CommonItemTooltip.PercentIncreasedDamage", 20)); 
// {0}% increased damage - where {0} is the damage increase (here it's 20)
```
image

### CODE REVIEW

**Comment by JavidPack** [comment]
Looking good. Other translators can finish out the other languages after this is merged, so just focus on the languages you know.

**Comment by Jofairden** [comment]
Are these kind of tooltips not in the vanilla files?

**Comment by Chik3r** [comment]
Some of these tooltips are in vanilla, but you can't give them your own numbers. For example, if I wanted a tooltip for increased movement speed, I could use `Language.GetTextValue("ArmorSetBonus.Ninja");` but it would return "20% increased movement speed" which wouldn't work if I wanted an increase of 18%.

**Comment by Mirsario** [comment]
The idea of integer-expecting strings like "{0}% decreased damage" seems very much fine, but people may shoot themselves in their knees by relying on partial strings like "Grants immunity to {0}" and "Increases {0} knockback", which will make accurate translations super hard in languages like Russian and Polish, due to abundance of grammatical cases.

**Comment by Chik3r** [comment]
So should I remove all partial strings, or leave the class strings but make a different key for each class (i.e: `"IncreaseKnockMagic": "Increases magic knockback", "IncreaseKnockMelee": "Increases melee knockback", ... "IncreaseDamageMelee": ...`)?
Also, sorry for taking so long to reply.

**Comment by JavidPack** [comment]
I think they are useful, even if not perfect in rare cases. Modders can always specify the russian translation in .lang files or code easily enough, if the grammar is important enough to fix.

**Comment by Chik3r** [comment]
Should I make a class containing constants for each tooltip? (If so, where?) This is so that you can autocomplete, and know what each key is about.
For example:
```cs
public class CommonItemTooltipKey {
  /// <summary> "{0}% increased damage" </summary>
  public const string PercentIncreasedDamage = "CommonItemTooltip.PercentIncreasedDamage";
  /// <summary> "{0}% increased melee damage" </summary>
  public const string PercentIncreasedDamage_Melee = "CommonItemTooltip.PercentIncreasedDamage_Melee";
  ...
  /// <summary> "Allows the holder to double jump" </summary>
  public const string AllowDoubleJump = "CommonItemTooltip.AllowDoubleJump";
}
```
and then
`Language.GetTextValue(CommonItemTooltipKey.PercentIncreasedDamage, 20);`

**Comment by JavidPack** [comment]
I don't think we want to maintain string consts. 

It all looks good, I still think we need
"PercentIncreasedDamage_Class": "{0}% increased {1} damage",
as well. We talked about russian having custom grammar rules, but I don't think we can avoid that right now. Add in the generic class ones and it should be fine

**Comment by Chik3r** [comment]
Added:
- `PercentIncreasedDamage_Class`
- `PercentDecreasedDamage_Class`
- `PercentIncreasedCritChance_Class`
- `PercentIncreasedDamageCritChance_Class`
- `IncreasesKnockback_Class`

**Comment by Mirsario** [comment]
Nice.

@JavidPack The idea is that we would have a method on DamageClass that would return the specific suffixed ClassName locale if it's defined, and just use the generic one if it's otherwise. Then modders who care enough will be able to add more accurate translations for their damage classes.

Though now that I think about it, the overrides should probably be somewhere under `Mods.X. ...` path.

**Comment by Chicken-Bones** [comment]
I've decided that custom classes are difficult to translate correctly, difficult to provide fallbacks for, and difficult to anticipate the desired combinations for. Thus it should fall on the implementor of a custom damage class to provide common tooltips for their class when localizing their mod.

I also think that the primary value here is numerical substitutions `{0}`. If you want a literal text line, chances are you can just reference it from a vanilla item, or copy the relevant tooltip portion.

After taking every vanilla tooltip containing a number, splitting on newlines and removing duplicates and small inconsistencies, there are 94 unique variations.
<details>

```
Absorbs {0}% of damage done to players on your team when above {0}% life
Activates every {0} seconds
Fishing line will never break, decreases chance of bait consumption, increases fishing power by {0}
Grants immunity to fire blocks and {0} seconds of immunity to lava
Hits quickly at the expense of {0}% tag damage
Ignores {0} points of enemy Defense
Increase defense by {0}
Increase your max number of sentries by {0}
Increases armor penetration by {0}
Increases arrow damage by {0}% and greatly increases arrow speed
Increases block placement and tool range by {0}
Increases block placement range by {0}
Increases bow damage by {0}%
Increases coin pickup range and shops prices lowered by {0}%
Increases critical chance by {0}%
Increases damage by {0}%
Increases defense by {0} when placed nearby
Increases fishing power by {0}
Increases gun damage by {0}%
Increases max life by {0}%
Increases maximum mana by {0}
Increases maximum mana by {0} and {0}% reduced mana cost
Increases mining speed by {0}%
Increases specialist ranged damage by {0}%
Increases summon damage by {0}%
Increases whip range by {0}%
Increases your max number of minions by {0}
Increases your max number of sentries by {0}
Increases your max number of sentries by {0} and increases melee speed by {0}%
Increases your max number of sentries by {0} and increases ranged critical strike chance by {0}%
Increases your max number of sentries by {0} and increases summon and melee damage by {0}%
Increases your max number of sentries by {0} and increases your life regeneration
Increases your max number of sentries by {0}, {0}% increased magic damage and {0}% reduced mana cost
Increases your summon damage by {0}% and the knockback of your minions
Permanently increases maximum life by {0}
Permanently increases maximum mana by {0}
Productivity up {0}%
Provides life regeneration and reduces the cooldown of healing potions by {0}%
Provides {0} seconds of immunity to lava
Puts a shell around the owner when below {0}% life that reduces damage by {0}%
Reduces damage taken by {0}%
Reduces the cooldown of healing potions by {0}%
Shoots {0} arrows at a time
Shops prices lowered by {0}%
Toss in water up to {0} times to increase fishing power
{0} summon tag damage
{0}% chance not to consume arrows
{0}% chance to not consume arrows
{0}% chance to not consume potion crafting ingredients
{0}% chance to save ammo
{0}% increased bow damage and {0}% increased arrow speed
{0}% increased critical strike chance
{0}% increased damage
{0}% increased damage and critical strike chance
{0}% increased damage and {0}% increased movement speed
{0}% increased magic and summon damage
{0}% increased magic critical strike chance
{0}% increased magic damage
{0}% increased magic damage and critical strike chance
{0}% increased magic damage and {0}% increased magic critical strike chance
{0}% increased melee and movement speed
{0}% increased melee and ranged critical strike chance
{0}% increased melee and ranged damage
{0}% increased melee critical strike chance
{0}% increased melee critical strike chance and {0}% increased movement speed
{0}% increased melee damage
{0}% increased melee damage and critical strike chance
{0}% increased melee damage and melee speed
{0}% increased melee damage and speed
{0}% increased melee speed
{0}% increased mining speed
{0}% increased movement and melee speed
{0}% increased movement speed
{0}% increased movement speed and {0}% increased damage
{0}% increased ranged critical strike chance
{0}% increased ranged damage
{0}% increased ranged damage and critical strike chance
{0}% increased summon and magic damage
{0}% increased summon and melee damage
{0}% increased summon and ranged damage and {0}% chance to save ammo
{0}% increased summon damage
{0}% increased summon damage and massively increased life regeneration
{0}% increased summon damage and melee critical strike chance
{0}% increased summon damage and melee speed
{0}% increased summon damage and ranged critical strike chance
{0}% increased summon damage and {0}% increased magic critical strike chance
{0}% increased summon damage and {0}% increased magic damage
{0}% increased summon damage and {0}% increased movement speed
{0}% increased summon damage and {0}% increased ranged critical strike chance
{0}% increased summon damage,
{0}% increased summon damage, {0}% increased magic critical strike chance and movement speed
{0}% increased summon damage, {0}% increased melee critical strike chance and movement speed
{0}% reduced mana cost
{0}% summon tag critical strike chance
```

</details>

I've elected not to include:
- Anything excessively specific/only used by 1 item in vanilla
- Combination tooltips, because the get out of hand pretty fast, and are often excessively specific.

Leaving the following 37 tooltips.
<details>

```
Increases defense by {0}
Increases armor penetration by {0}

Increases maximum life by {0}
Increases maximum mana by {0}
Increases maximum life by {0}%
Increases maximum mana by {0}%

Increases bow damage by {0}%
Increases gun damage by {0}%
Increases specialist ranged damage by {0}%

Increases whip range by {0}%
Increases your max number of minions by {0}
Increases your max number of sentries by {0}

Increases fishing power by {0}

Permanently increases maximum life by {0}
Permanently increases maximum mana by {0}

Reduces damage taken by {0}%

{0}% chance to save ammo
{0}% reduced mana cost

{0}% increased mining speed
{0}% increased movement speed

{0} armor penetration
{0}% increased damage
{0}% increased critical strike chance
{0}% increased damage and critical strike chance

{0}% increased magic damage
{0}% increased magic critical strike chance
{0}% increased magic damage and critical strike chance

{0}% increased melee damage
{0}% increased melee critical strike chance
{0}% increased melee damage and critical strike chance
{0}% increased melee speed

{0}% increased ranged damage
{0}% increased ranged critical strike chance
{0}% increased ranged damage and critical strike chance

{0}% increased summon damage
{0} summon tag damage
{0}% summon tag critical strike chance
```

</details>

I'll be implementing this as part of the localization rework (#3101) and applying it throughout Example Mod

I'm open to more common tooltip suggestions (particularly reduction versions), if there's evidence of them being used in multiple mods.

**Comment by Chicken-Bones** [comment]
Addressed in 90a072bf6150952cbdb4164bce5d2fc27c2ddc1a

**Pull request closed without merging**
