### PR TITLE
OnStartDay and OnStartNight hooks

### PR DESCRIPTION
**Pull request by Cyrillya**
### What is the new feature?
Added `OnStartDay` and `OnStartNight` hooks to ModSystem.
### Why should this be part of tModLoader?
Useful if you want to start a invasion or spawn a boss when day/night starts.
### Sample usage for the new feature
Spawn a boss naturally at night like EoC.
### ExampleMod updates
Each night the Minion Boss has a 10% chance of being spawned naturally if it is not downed.

### CODE REVIEW

**Comment by direwolf420** [comment]
So the main selling point of this PR is the ability to prevent natural boss/invasions from occuring? Because doing code on day start/end is already possible using existing ModSystem hooks by checking Main.time and Main.dayTime

**Comment by Cyrillya** [comment]
I just realized that we can use `Main.time` and `Main.dayTime`. So these hooks may be useless

**Comment by steviegt6** [comment]
These seem convenient enough to be justifiable, it at least reduces boilerplate on the modder's side.

**Comment by JavidPack** [comment]
At the very least someone can PR an example of a nightly or morning event with random chance for ExampleMod, just to show the correct code. Even a simple Main.NewText("You think today will be really cool for no reason") would suffice.

**Pull request closed without merging**
