### PR TITLE
[1.4.4] Updated Shimmered Example NPCs and Added Gore

### PR DESCRIPTION
**Pull request by Rijam**
### What are the changes to ExampleMod?

Updates the shimmered Example Person, Example Traveling Merchant, and adds shimmered Example Bone Merchant. Gore for all three of those NPCs were added. I also added/clarified some comments in Example Person.

Remaining issues:
* **I've created 3 styles for creating the gore (one style for each NPC). Tell me which style is the best and I will update the other two to match.**
* Example Bone Merchant has their shimmer texture while in the Bestiary if they are shimmered.
* Not directly Terraria/tModLoader's fault, but trying to check for `NPC.IsShimmerVariant` in `SetupShop()` will always be false. Vanilla doesn't do anything with this, but I know some modders will want to have special shop items when their Town NPC is shimmered. One way around this is to just check something like `Main.npc[NPC.FindFirstNPC(ModContent.NPCType<ExamplePerson>())].IsShimmeredVariant` in the shop. That's not super elegant, though.

If anyone has opinions regarding naming and/or whether we should put the shimmered textures in a Shimmered folder, let me know. 

I could also add something like
```cs
public override void PostAI() => NPC.color = NPC.IsShimmerVariant ? Main.DiscoColor : default; // Make the color of the NPC rainbow when shimmered.
```
if we wanted to show off some different possibilities.

### Do these changes need additional documentation?

No, but I am planning on making a Town NPC guide in the future.

<details><summary>Old description</summary><blockquote>

### What are the changes to ExampleMod?

Adds a shimmered form to the Example Person. I also added/clarified some comments in Example Person.

Big remaining issues:
* The head icon doesn't change when being shimmered, unlike vanilla. Setting multiple textures with conditions in `GetHeadTextureIndex()` will result in the head icon to be invisible and an index out of bounds error. Perhaps we need a `AutoloadShimmeredHead` attribute or something?
* The shimmer state doesn't save when exiting and rejoining the world. Perhaps we need to save it in `SaveData()` and `LoadData()` hooks? `NPC.IsShimmeredVariant` is read only I'm pretty sure, so we'd have to do something else.
* Not directly Terraria/tModLoader's fault, but trying to check for `NPC.IsShimmerVariant` in `SetupShop()` will always be false. Vanilla doesn't do anything with this, but I know some modders will want to have special shop items when their Town NPC is shimmered. One way around this is to just check something like `Main.npc[NPC.FindFirstNPC(ModContent.NPCType<ExamplePerson>())].IsShimmeredVariant` in the shop. That's not super elegant, though.

If anyone has opinions regarding naming and/or whether we should put the shimmered textures in a Shimmered folder, let me know. 

I could also add something like
```cs
public override void PostAI() => NPC.color = NPC.IsShimmerVariant ? Main.DiscoColor : default; // Make the color of the NPC rainbow when shimmered.
```
if we wanted to show off some different possibilities.

I also wanted to know if I should add gore to Example Person. 

### Do these changes need additional documentation?

No, unless we want to make a Town NPC Guide or something like that, which I would be ok with making.

</blockquote></details>

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
- Shimmered head icons need investigating.
- Variants not saving is known, and listed in the porting notes as a todo
- `SetupShop` is related to #3152

**Comment by Rijam** [comment]
I added the Example Bone Merchant because the vanilla Skeleton Merchant can be shimmered. However, I noticed the Bestiary was showing the shimmered texture even when the ITownNPCProfile says not to.

I tried to fix the issue of modded Town NPCs not saving their shimmer state with (in `WorldIO.cs`):
```patch
	internal static List<TagCompound> SaveNPCs()
				...
				if (npc.townNPC) {
					tag["displayName"] = npc.GivenName;
					tag["homeless"] = npc.homeless;
					tag["homeTileX"] = npc.homeTileX;
					tag["homeTileY"] = npc.homeTileY;
+					tag["townNpcVariationIndex"] = npc.townNpcVariationIndex;
				}
	...
	internal static void LoadNPCs(IList<TagCompound> list)
				...
				if (npc.townNPC) {
					npc.GivenName = (string)tag["displayName"];
					npc.homeless = tag.GetBool("homeless");
					npc.homeTileX = (int)tag["homeTileX"];
					npc.homeTileY = (int)tag["homeTileY"];
+					npc.townNpcVariationIndex = tag.GetInt("townNpcVariationIndex");
				}
	...
```
and it worked! ... until the world sometimes decided not to load. So, somebody who actually knows what they are doing should probably take a look at it. `NPC.ShimmeredTownNPCs[]` is probably what should be used instead anyway.

**Comment by Rijam** [comment]
I've created 3 styles for creating the gore (one style for each NPC). Tell me which style is the best and I will update the other two to match.

**Comment by JavidPack** [comment]
Thanks a bunch!

**Pull request merged**
