### PR TITLE
Add mod support for taller head armor sprites

### PR DESCRIPTION
**Pull request by Cerbrus**
### What is the new feature?
Support for taller head armor sprites like the wizard's hat
Reported at: #2923

### Why should this be part of tModLoader?
This makes it possible to add head armor in mods with taller head armor sprites, like wizard's hats.

### Are there alternative designs?
This solution was suggested in the reported issue.

I renamed the `flag` boolean to the more descriptive `isTallHat`.

### Sample usage for the new feature
If you're adding a new head armor item, you can enable taller sprite rendering with the following line:

```
ArmorIDs.Head.Sets.IsTallHat[Item.headSlot] = true;
```

### ExampleMod updates

I've added a `ExampleTallHelmet`  (ingame "Example Tall Helmet") to show it functioning.

### CODE REVIEW

**Comment by JavidPack** [comment]
Thanks for this. I wasn't sure if the textures from the issue were free to use, so I swapped them out. I also fixed a bug when drawinfo.drawPlayer.head is -1, meaning no helmet is equipped.

**Comment by JavidPack** [comment]
Some Notes: 
Also, I decided against adding support for extra wide helmets, because it wouldn't be easy to support even taller helmets without enforcing some specific arbitrary layout choices. I'll leave that to modders.

**Comment by Cerbrus** [comment]
> Thanks for this. I wasn't sure if the textures from the issue were free to use, so I swapped them out. I also fixed a bug when drawinfo.drawPlayer.head is -1, meaning no helmet is equipped.  

You're welcome!

I'm new to contributing here, so your changes are welcome 😃 

I was curious, I see you changed the flag name back to `flag`, why is that?

**Comment by JavidPack** [comment]
> I was curious, I see you changed the flag name back to `flag`, why is that?

I changed it back because we try to minimize the patches. 

When Terraria updates, there is a process of migrating patches to the new decompiled source code, that process requires us to review any patch in methods that changed since last version. It's easier to maintain if it's just a single change, if it's 2 changes then there is a possibility that we make a mistake and what used to be `flag` is now `flag3` and we miss updating one or the other patch, resulting in bugs. 

We don't always minimize to this extent, such as with confusing variables, but the intent of `flag` is easy enough to follow that it's easier to leave it as flag.

**Comment by Cerbrus** [comment]
> > I was curious, I see you changed the flag name back to `flag`, why is that?
> 
> I changed it back because we try to minimize the patches. <....>


Ah, that makes a lot of sense! Thanks for the explanation!

**Pull request merged**
