### PR TITLE
New Workshop Menu Icons

### PR DESCRIPTION
**Pull request by Rijam**
### What is the new feature?
I have changed the icons for the Manage Mods, Develop Mods, Download Mods, and Mod Packs to better show that they are for mods/tModLoader.

(Updated!)

Screenshot with proposed icons (alternate versions below).
RealInGameCaptureV2

Here are the icons (or get them from the commit)
HubManageMods Manage Mods
HubDownloadMods Download Mods
HubModPacks Mod Packs
HubDevelopMods Develop Mods

### Why should this be part of tModLoader?
The current icons in the Workshop Menu don't really reflect mods or tModLoader. Mod Packs has a tree with an upload cloud? These new icons are much more obvious at what they do.

### Are there alternative designs?
Code wise: (Updated) I have changed the implementation based on Solxan's comments. Let me know if something needs to be changed further.

Image wise: I have come up with some different icons. Use these if you feel like they suit the button better.
HubDevelopMods_Alt7 Develop Mods
HubDownloadMods_Alt1 Download Mods (Outdated image)

Extras if anyone wants them:
Default NewBackground (Thanks jackbondpreston for the corrected background.)

### CODE REVIEW

**Comment by Rijam** [comment]
Here is a screenshot of the current menu. The icons for the mod related stuff currently share vanilla icons for resource packs and worlds. It isn't really obvious of what their function is. The new icons make it much more obvious that they are related to mods.
CurrentMenu

Clarification on why this is a draft: I would like feedback on which icons to use and how to better implement them in into tModLoader (code wise).

**Comment by ghost** [comment]
The icons look great. I've always though the upload-looking icon for Develop Mods was a bit misleading, as the menu isn't only used for publishing - so I personally prefer all of your alternative designs for that over the upload-looking one.

I think @Solxanich implemented the original menu, so they would be able to help you with implementation (they're ill right now so I'm sure it will be a while until they have time to look at it)

**Comment by Solxanich** [comment]
I am alive and reading yes.

From proposed:
Download Mods - yes
Manage Mods - yes
Mod Packs - Maybe
Develop Mods - no, doesn't feel right.

I like the hammer better for the develop mods menu. 

That said, just my opinion, would prefer review icons in collaborators since UI can get heavily opinionated.

**Comment by Rijam** [comment]
Yeah, the more I look at it, the more I like the right facing wrench or the hammer better for the Develop Mods button. I don't have the contributor role so I can't talk in the collaborators channel on the Discord.
Did you take a look at the code? I also need feedback there. As stated above, it doesn't give the highlighted outline like the vanilla icons, even though I copied the same code.

**Comment by ghost** [comment]
> Yeah, the more I look at it, the more I like the right facing wrench or the hammer better for the Develop Mods button. I don't have the contributor role so I can't talk in the collaborators channel on the Discord.

You can DM or @ someone on Discord for the role (can post this PR to show you are contributing)

**Comment by AZaurelli** [comment]
Went to go download mods and noticed the change to the icons. Honestly love them. They fit into tModloader so  perfectly. Might be a small change but it makes the menu look so much better. <3

**Pull request merged**
