### PR TITLE
Updated Brazilian Portuguese version of tModLoader.json.

### PR DESCRIPTION
**Pull request by tomazneves**
### What is the issue?
pt-BR/tModLoader.json was lacking translations.

### How did you fix the issue?
By translating all untranslated parts.

### Are there alternatives to your fix?
There are some parts that could be reworded, especially the ones concerning programming jargon (i.e. "namespace", "building", etc.) that can't be properly localized to portuguese (to the best of my knowledge).

### CODE REVIEW

**Comment by Jofairden** [comment]
Could you update this, as per #1119 ?

**Comment by Solxanich** [comment]
@pombozap ;
Hello, was hoping you might be able to let us know if you intend to return to this PR and address Jofairden's question and any merge conflicts?
Note that the localization file appears to have been updated since, although I don't know enough to know if that update covers the contents of this PR; feel free to close this if that's the case.

Thank you for your time.

**Comment by pombozap** [comment]
Hi! Sorry for the absence, I got busy with some Uni work and forgot about it.
From what I could gather with a quick read, the mentioned update ("as per #1119") is still pending. I am not that experienced with github, so from what I can tell the update has changed the base json's structure, but the brazilian portuguese translation is still formatted as per the old method, and as such is conflicting. Feel free to correct me if that's the case.
I'll try to finish it this week. Thanks for the head's up.

**Comment by Solxanich** [comment]
No worries! It's a community contribution project so its always able to idle on some things. Just thought I'd drop a ping like I have on other PRs that had likely been forgotten after 4+ months away, since happens often enough.

At any rate, right on the nose it seems, should only need to update the file to the new format mentioned. Take your time, university can be demanding at the best of times

**Comment by pombozap** [comment]
Took me some time, but was finally able to get back to this. I saw another pull request (I think?) that had something to do with the pt-BR translation though, which I haven't checked to see if either resolved or conflicts with some of these fixes. Anyway, I hope it all works, and I'm, again, sorry for the delay.

**Comment by pombozap** [comment]
PS.: I haven't quite gotten the hang of GitHub yet, so I don't really know if I should close this or not? Sorry for any inconveniences.

**Comment by JavidPack** [comment]
I'm seeing a lot of places where you accidentally replaced tabs with spaces, for example here: https://github.com/tModLoader/tModLoader/pull/1116/files#diff-a1cb8c01609cfd45960f56805f24ae77417d993df8a4826aa3461a8be86a79e7R11

If you can fix those up, this looks fine. The other PR was for 1.3, so a lot of what you are translating are new keys, but I think the two of you might be duplicating work. You might want to double check with the master branch and see if any of those changes are better than your translations, for the ones that were recently added there.

**Comment by xNarnia** [comment]
Tab spacing fix for this PR has been requested here. Awaiting @pombozap's acceptance
https://github.com/pombozap/tModLoader/pull/1

If no movement is made on this PR, the updated translation file can be found here
[BR Translation JSON.zip](https://github.com/tModLoader/tModLoader/files/7728490/BR.Translation.JSON.zip)

**Comment by JavidPack** [comment]
Looks like most the translations have already been integrated. Sorry we missed each other while dealing with changes to the format. Closing.

**Pull request closed without merging**
