### PR TITLE
Active Entity Iterators

### PR DESCRIPTION
**Pull request by BasicallyIAmFox**
### What is the new feature?

Added `Main.ActiveNPCs` `ActiveProjectiles`, `ActivePlayers` and `ActiveItems` which can be used in `foreach` statements.

Benchmarking has been included to provide evidence that these iterators have no significant performance costs. In fact, the unsafe version is slightly faster.

<details>
  <summary>Benchmarking Results</summary>
  
```

BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3296/23H2/2023Update/SunValley3)
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.101
  [Host]     : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2

```

| Method                                 | Categories | Mean         | Error       | StdDev       | Median       | Ratio | RatioSD |
|--------------------------------------- |----------- |-------------:|------------:|-------------:|-------------:|------:|--------:|
| NPCProjectileCollisions_ForLoop        | Collision  | 198,979.7 ns | 7,133.70 ns | 21,033.88 ns | 192,984.0 ns |  1.00 |    0.00 |
| NPCProjectileCollisions_SpanLoop       | Collision  | 197,754.0 ns | 5,086.59 ns | 14,997.94 ns | 196,648.9 ns |  1.01 |    0.14 |
| NPCProjectileCollisions_Iterator       | Collision  | 257,799.6 ns | 9,627.90 ns | 28,388.09 ns | 258,984.0 ns |  1.31 |    0.19 |
| NPCProjectileCollisions_IteratorUnsafe | Collision  | 139,779.5 ns | 3,192.17 ns |  9,158.94 ns | 139,282.2 ns |  0.72 |    0.08 |
|                                        |            |              |             |              |              |       |         |
| DistanceSq_ForLoop                     | DistanceSq |     301.5 ns |     1.57 ns |      1.39 ns |     301.3 ns |  1.00 |    0.00 |
| DistanceSq_SpanLoop                    | DistanceSq |     306.6 ns |     4.08 ns |      3.82 ns |     305.4 ns |  1.02 |    0.01 |
| DistanceSq_Iterator                    | DistanceSq |     335.9 ns |     6.53 ns |      5.46 ns |     334.2 ns |  1.11 |    0.02 |
| DistanceSq_IteratorUnsafe              | DistanceSq |     299.0 ns |     3.49 ns |      3.26 ns |     298.9 ns |  0.99 |    0.01 |
|                                        |            |              |             |              |              |       |         |
| Simple_ForLoop                         | Simple     |     198.6 ns |     5.17 ns |     15.17 ns |     197.6 ns |  1.00 |    0.00 |
| Simple_SpanLoop                        | Simple     |     240.6 ns |     3.71 ns |      3.47 ns |     240.0 ns |  1.15 |    0.07 |
| Simple_Iterator                        | Simple     |     228.0 ns |     4.54 ns |     11.87 ns |     229.0 ns |  1.13 |    0.11 |
| Simple_IteratorUnsafe                  | Simple     |     154.1 ns |     2.30 ns |      2.15 ns |     154.2 ns |  0.73 |    0.04 |
|                                        |            |              |             |              |              |       |         |
| SimpleType_ForLoop                     | SimpleType |     128.7 ns |     2.34 ns |      3.77 ns |     128.3 ns |  1.00 |    0.00 |
| SimpleType_SpanLoop                    | SimpleType |     136.8 ns |     2.52 ns |      6.05 ns |     135.4 ns |  1.08 |    0.05 |
| SimpleType_Iterator                    | SimpleType |     137.1 ns |     2.64 ns |      5.80 ns |     136.3 ns |  1.07 |    0.06 |
| SimpleType_IteratorUnsafe              | SimpleType |     114.3 ns |     1.47 ns |      1.38 ns |     114.5 ns |  0.88 |    0.03 |

</details>

### Why should this be part of tModLoader?
Modder convenience. Due to the last entry in the arrays being a 'dummy' and having to check `.active` on all entities, modders were forced to write quite a bit of boilerplate when looping over entities in the world.

```cs
for (int i = 0; i < Main.maxNPCs; i++) {
  var npc = Main.npc[i];
  if (!npc.active) continue;
  // Code
}
```

### Are there alternative designs?
A higher performance version is present in the `test/EntityIteratorsPerformance/Benchmarks.cs` using `ref` fields which we can switch to once we move to .NET 8 with #4037 

### Sample usage for the new feature
```cs
foreach (var npc in Main.ActiveNPCs) {
  // Code
}
```

### ExampleMod updates
Updated most NPC, Projectile and Player loops.

### CODE REVIEW

**Comment by JackerAcid** [comment]
I know this might be a bit semantic, but I feel like `activeNpcs` should be changed to `activeNPCs` to be consistent.

**Comment by BasicallyIAmFox** [comment]
> I know this might be a bit semantic, but I feel like `activeNpcs` should be changed to `activeNPCs` to be consistent.

wait until you see `Conditions.NpcIsPresent`

**Comment by JackerAcid** [comment]
> > I know this might be a bit semantic, but I feel like `activeNpcs` should be changed to `activeNPCs` to be consistent.
> 
> wait until you see `Conditions.NpcIsPresent`

Well... atleast to be consistent with the thing you propose it replaces the use for.

**Comment by BasicallyIAmFox** [comment]
> > > I know this might be a bit semantic, but I feel like `activeNpcs` should be changed to `activeNPCs` to be consistent.
> > 
> > 
> > wait until you see `Conditions.NpcIsPresent`
> 
> Well... atleast to be consistent with the thing you propose it replaces the use for.

`Main.npc` not being `Main.NPC`

**Comment by JackerAcid** [comment]
> > > > I know this might be a bit semantic, but I feel like `activeNpcs` should be changed to `activeNPCs` to be consistent.
> > > 
> > > 
> > > wait until you see `Conditions.NpcIsPresent`
> > 
> > 
> > Well... atleast to be consistent with the thing you propose it replaces the use for.
> 
> `Main.npc` not being `Main.NPC`

Fair enough I guess

**Comment by JavidPack** [comment]
Just a reminder to myself: 

We had discussed `Item.whoAmI` being out of sync sometimes (for at least part of an update), and therefore was unreliable, but didn't remember where it happened. I just noticed that `Player.PickupItem` is one place where that appears to happen.

**Pull request merged**
