### PR TITLE
Updated some documentation

### PR DESCRIPTION
**Pull request by mtkloepf**
### What is the new feature?
Resolves issue  #3316 

Documentation updated for:
* DamageClass and all implementations of CountsAsClass( )
* StatModifier.ApplyTo( )
* GetTotalDamage( ) functions

### Why should this be part of tModLoader?
Updates add more clarity for function usage - especially APIs important to modders

### Are there alternative designs?
Documentation is always a subjective effort :)

### Sample usage for the new feature
n/a

### ExampleMod updates

### CODE REVIEW

**Comment by noctisatrae** [comment]
> Documentation is always a subjective effort :)

Love this ❤️! Good PR, I think you're being pretty clear stating what you want to do!  I'm also rewriting a very specific part of the documentation, could you review it at #3378 ?

**Comment by mtkloepf** [comment]
@JavidPack Please review at your leisure.

**Comment by JavidPack** [comment]
Looks good, thanks. In the future, `<seealso>` and `<example>` are not useful, since they don't show up in the intellisense box.

**Comment by mtkloepf** [comment]
> Looks good, thanks. In the future, `<seealso>` and `<example>` are not useful, since they don't show up in the intellisense box.

I suppose there's an argument for using `<see>` instead, but example and SA will show in the online documentation if we upload the new version. That was my main target. Good to know your thoughts though.

**Comment by JavidPack** [comment]
Our online documentation will probably do something with them, but that's definitely not where our modders would be looking for relevant information.

**Comment by noctisatrae** [comment]
:D I look at it a lot actually to see the arguments needed for a function & class.

**Comment by JavidPack** [comment]
Yes, it is an option, but the expectation is your IDE should be showing you all the information already.

**Pull request merged**
